name: Python Syntax Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # specify your desired Python version

    - name: Install dependencies
      run: |
        pip install flake8

    - name: Run flake8 on changed files
      run: |
        # Check only the files that have changed
        changed_files=$(git diff --name-only origin/main...HEAD)
        if [ -z "$changed_files" ]; then
          echo "No Python files have changed."
        else
          flake8 $changed_files
        fi
